version: 2
jobs:
  unit_tests:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - flambe-cache-{{ .Branch }}
              - flambe-cache-
        - run: python3 -m pip install --user tox awscli
        - run: python3 -m awscli configure set region us-east-1
        - run:
            command: python3 -m tox -- -m "not end2end and not examples" -v
            no_output_timeout: 30m
        - save_cache:
            paths:
              - ~/.cache/pip
            key: flambe-cache-{{ .Branch }}
        - store_test_results:
            path: test_results
        - store_artifacts:
            path: test_results
  end2end_tests:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: python3 -m pip install --user tox awscli
        - run: python3 -m awscli configure set region us-east-1
        - run:
            command: python3 -m tox -- -m "end2end" -sv
            no_output_timeout: 180m
        - save_cache:
            paths:
              - ~/.cache/pip
            key: flambe-cache-{{ .Branch }}
        - store_test_results:
            path: test_results
        - store_artifacts:
            path: test_results
  examples_tests:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: python3 -m pip install --user tox awscli
        - run: python3 -m awscli configure set region us-east-1
        - run:
            command: python3 -m tox -- -m "examples" -sv
            no_output_timeout: 180m
        - save_cache:
            paths:
              - ~/.cache/pip
            key: flambe-cache-{{ .Branch }}
        - store_test_results:
            path: test_results
        - store_artifacts:
            path: test_results
  publish-test:
      docker:
          - image: python:3.6
      steps:
        - checkout
        - run: python3 -m pip install --user twine
        - run: python3 setup.py sdist bdist_wheel
        - run: python3 -m twine upload -u $TWINE_TEST_USERNAME -p $TWINE_TEST_PASSWORD --repository-url $PYPI_TEST_URL dist/*
  publish:
      docker:
          - image: python:3.6
      steps:
        - checkout
        - run: python3 -m pip install --user twine
        - run: python3 setup.py sdist bdist_wheel
        - run: python3 -m twine upload --repository-url $PYPI_URL dist/*

workflows:
  version: 2
  build:
    jobs:
      - unit_tests:
          filters:
            tags:
              only:
                - /.*/
      - end2end_tests:
          filters:
            tags:
              only:
                - /.*/
      - examples_tests:
          requires:
            - end2end_tests
            - unit_tests
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /.*/
      - publish-test:
          context: flambe-publisher
          requires:
            - end2end_tests 
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - publish:
          context: flambe-publisher
          requires:
            - publish-test
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
